name: pagermaid build

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Optional: Specify a commit hash to build'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      UPSTREAM_REPO: https://github.com/outlook84/PagerMaid-Modify.git
      WORKDIR: pagermaid

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v6

      - name: Create workdir
        run: mkdir -p ./${{ env.WORKDIR }}

      - name: Clone repository
        working-directory: ./${{ env.WORKDIR }}
        run: |
          if [ -z "${{ github.event.inputs.commit_hash }}" ]; then
            echo "Cloning the latest version..."
            git clone --depth 1 -b dev "$UPSTREAM_REPO" .
          else
            echo "Cloning the full repository to checkout commit ${{ github.event.inputs.commit_hash }}..."
            git clone -b dev "$UPSTREAM_REPO" .
            echo "Checking out commit ${{ github.event.inputs.commit_hash }}..."
            git checkout ${{ github.event.inputs.commit_hash }}
          fi

      - name: Append google-genai to requirements.txt
        working-directory: ./${{ env.WORKDIR }}
        run: |
          echo -e "\ngoogle-genai" >> ./requirements.txt
          echo -e "\ntelegraph[aio]" >> ./requirements.txt
          echo -e "\nmarkdown" >> ./requirements.txt
          echo -e "\nbeautifulsoup4" >> ./requirements.txt
          echo -e "\nemoji" >> ./requirements.txt
          echo -e "\nregex" >> ./requirements.txt
          echo -e "\nfonttools" >> ./requirements.txt
          echo -e "\nqrcode[pil]" >> ./requirements.txt
          echo -e "\npyzbar" >> ./requirements.txt
          sed -i 's|libmagic|libmagic ffmpeg|' ./Dockerfile.alpine
          sed -i 's|pip install -r requirements.txt|pip install git+https://github.com/outlook84/FastTelethonhelper.git \&\& pip install -r requirements.txt|' ./Dockerfile.alpine

      - name: Get upstream commit SHA
        working-directory: ./${{ env.WORKDIR }}
        id: get_upstream_sha
        run: |
          UPSTREAM_SHA=$(git rev-parse HEAD)
          echo "Upstream commit SHA is $UPSTREAM_SHA"
          echo "upstream_sha=$UPSTREAM_SHA" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tag from date
        id: date_tag
        run: |
          DATE_TAG=$(date +%F)
          echo "date_tag=$DATE_TAG" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/outlook84/pagermaid-modify
          tags: |
            type=raw,enable=true,value=${{ steps.date_tag.outputs.date_tag }}
            type=sha,sha=${{ steps.get_upstream_sha.outputs.upstream_sha }},format=short
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "./${{ env.WORKDIR }}"
          file: ./${{ env.WORKDIR }}/Dockerfile.alpine
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
